@praktyki_HostAddress = https://localhost:7012

GET {{praktyki_HostAddress}}/weatherforecast/
Accept: application/json

###

@Number=string
GET {{praktyki_HostAddress}}/api/verifypesel/03262004174

###

GET {{praktyki_HostAddress}}/api/verifypesel/{{Number}}

###

GET {{praktyki_HostAddress}}/api/verifypesel/03262004176

###
