@praktyki-vies_HostAddress = https://localhost:7162
@praktyki_vies_HostAddress = http://localhost:5116

GET {{praktyki_vies_HostAddress}}/weatherforecast/
Accept: application/json

###

@countryCode=string
@taxId=string
GET {{praktyki-vies_HostAddress}}/api/verifyvies/{{countryCode}}/{{taxId}}

###

GET {{praktyki-vies_HostAddress}}/api/verifyvies/{{countryCode}}/{{taxId}}

###

GET {{praktyki-vies_HostAddress}}/api/verifyvies/{{countryCode}}/vat/{{taxId}}

###
